export enum SocketEventType {
	SEND_MESSAGE = 'sendMessage',
	UPDATE_EXTRA_DATA = 'updateExtraData',
	USER_DISCONNECTED = 'userDisconnected',
	SET_USER_DATA = 'setUserData',
	GET_ALL_USERS = 'getAllUsers',
	JOIN_ROOM = 'joinRoom',
	ROOM_USER_COUNTS = 'roomUserCounts',
	GET_IP = 'getIP',
	DOUBLE_LOGIN = 'doubleLogin',
	PRIVATE_CALL = 'privateCall',
	CALL_ENDED = 'callEnded',
	RESET_CHAT_FOR_ALL = 'resetChatForAll',
	USER_CONNECTED = 'userConnected',
	SETTINGS_UPDATED = 'settingsUpdated',
	USER_UPDATED = 'userUpdated',
	ROOM_UPDATED = 'roomUpdated',
}
