### Find a particular user with a given ID
GET http://localhost:3000/api/auth/4

### Find all users with a given username
GET http://localhost:3000/api/auth?username=test1@test.com

### Delete a user given id
DELETE http://localhost:3000/api/auth/3

### Update a user
PATCH http://localhost:3000/api/auth/1
content-type: application/json

{
  "password": "aaaaa"
}

### Validate user
POST http://localhost:3000/api/auth/validateUser
content-type: application/json

{
  "username": "tufan"
}

### Deneme
POST http://localhost:3000/api/users/deneme
content-type: application/json

{
  "username": "test3"
}