### Create a new user
POST http://localhost:3000/api/auth/signup
content-type: application/json

{
  "username": "tufan",
  "password": "12345",
  "gender": true
}

### Sign in as an existing user
POST http://localhost:3000/api/auth/signin
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Get the currently signed in user
GET http://localhost:3000/api/auth/whoami

### Sign out
POST http://localhost:3000/api/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/api/auth/4

### Find all users with a given email
GET http://localhost:3000/api/auth?email=test1@test.com

### Delete a user given id
DELETE http://localhost:3000/api/auth/3

### Update a user
PATCH http://localhost:3000/api/auth/1
content-type: application/json

{
  "password": "aaaaa"
}

### Validate user
POST http://localhost:3000/api/auth/validateUser
content-type: application/json

{
  "username": "tufan"
}

### Visitor login
POST http://localhost:3000/api/auth/visitorLogin
content-type: application/json

{
  "username": "tufan2"
}