### Create a new room
POST http://localhost:3000/api/room
Content-Type: application/json

{
    "name": "Room 3",
    "row": 0,
    "active": true,
    "default": true
}


### Get All
GET http://localhost:3000/api/room

### Get One
GET http://localhost:3000/api/room/3


### Update room
PATCH http://localhost:3000/api/room/1
Content-Type: application/json

{
    "name": "Room 3",
    "row": 1,
    "default": true,
    "bg": "https://www.w3schools.com/tags/img_girl.jpg",
    "password": "123"
}

### Delete room
DELETE http://localhost:3000/api/room/3